Library/Models/Book.cs
namespace Library.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Autor { get; set; }
        public string Genre { get; set; }
        public string Description { get; set; }
        public double Rating { get; set; }
        public bool IsRead { get; set; }
        public int? UserID { get; set; }
        public User User { get; set; }

    }
}

Library/Models/ErrorViewModel.cs
namespace Library.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Library/Models/LibContext.cs
using Microsoft.EntityFrameworkCore;

namespace Library.Models
{
    public class LibContext : DbContext
    {
        public DbSet<Book> Books { get; set; } = null!;
        public DbSet<User> Users { get; set; } = null!;
        public LibContext(DbContextOptions<LibContext> options) : base(options)
        {
            //Database.EnsureDeleted();
            Database.EnsureCreated();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>().HasData(
                 new User
                 {
                     Id = 1,
                     Name = "Никита"
                 },
                new User
                {
                    Id = 2,
                    Name = "Макс"
                }

                );
            modelBuilder.Entity<Book>().HasData(
                new Book
                {
                    Id = 1,
                    Title = "Ведьмак1",
                    Autor = "Сапковский",
                    Genre = "Фэнтези",
                    Description = "12356134gufherv",
                    Rating = 4.6,
                    IsRead = true,
                    UserID = 1
                },
                new Book
                {
                    Id = 2,
                    Title = "Ведьмак2",
                    Autor = "Сапковский",
                    Genre = "Фэнтези",
                    Description = "12356134gufherv",
                    Rating = 4.6,
                    IsRead = true,
                    UserID = 2
                },
                new Book
                {
                    Id = 3,
                    Title = "Ведьмак3",
                    Autor = "Сапковский",
                    Genre = "Фэнтези",
                    Description = "12356134gufherv",
                    Rating = 4.6,
                    IsRead = true,
                    UserID = 2
                }
                );
        }
    }
}

Library/Models/User.cs
namespace Library.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public IEnumerable<Book> Books { get; set; }
    }
}

Library/ViewModels/BookModel.cs
namespace Library.ViewModels
{
    public record class BookModel (int Id, string Title, string Autor, string Genre, string Description, double Rating, bool IsRead, int? UserID);
    
}

Library/ViewModels/IndexViewModel.cs
using Library.Models;

namespace Library.ViewModels
{
    public class IndexViewModel
    {
        public IEnumerable<Book> Books { get; set; } = new List<Book>();
        public IEnumerable<UserModel> Users { get; set; } = new List<UserModel>();
        public IEnumerable<BookModel> BookModels { get; set; } = new List<BookModel>();
    }
}

Library/ViewModels/UserModel.cs
namespace Library.ViewModels
{
    public record class UserModel (int id, string Name);
    
}

Library/Controllers/BookController.cs
using Microsoft.EntityFrameworkCore;
using Library.Models;
using Microsoft.AspNetCore.Mvc;
using Library.ViewModels;

namespace Library.Controllers
{
    public class BookController : Controller
    {
        private readonly ILogger<BookController> _logger;

        LibContext db;
        public BookController(LibContext context, ILogger<BookController> logger)
        {
            _logger = logger;
            db = context;
        }
        public async  Task<IActionResult> Index()
        {
            return View(await db.Books.ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Book book)
        {
            List<UserModel> userModels = db.Users.Select(u => new UserModel(u.Id, u.Name)).ToList();
            IndexViewModel viewModel = new()
            {
                Users = userModels
            };

            


            db.Books.Add(book);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Book? book = await db.Books.FirstOrDefaultAsync(p => p.Id == id);
                if (book != null)
                {
                    db.Books.Remove(book);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Book? book = await db.Books.FirstOrDefaultAsync(p => p.Id == id);
                if (book != null) return View(book);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Book book)
        {
            db.Books.Update(book);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Library/Controllers/HomeController.cs
using Library.Models;
using Library.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        LibContext db;

        public HomeController(ILogger<HomeController> logger, LibContext context)
        {
            db = context;
            _logger = logger;
        }

        public IActionResult Index (int? userId)
        {
            List<UserModel> userModels = db.Users.Select(u => new UserModel(u.Id, u.Name)).ToList();
            userModels.Insert(0, new UserModel(0, "Все"));

            IndexViewModel viewModel = new()
            {
                Users = userModels,
                Books = db.Books
            };

            if (userId != null && userId > 0)
                viewModel.Books = db.Books.Where(b => b.User.Id == userId);

            return View(viewModel);
        }

        

        
    }
}

Library/Controllers/UserController.cs
using Microsoft.EntityFrameworkCore;
using Library.Models;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    public class UserController : Controller
    {
        LibContext db;

        public UserController(LibContext context)
        {
            db = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await db.Users.ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(User user)
        {
            db.Users.Add(user);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                User? user = await db.Users.FirstOrDefaultAsync(u => u.Id == id);
                if (user != null)
                {
                    db.Users.Remove(user);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                User? user = await db.Users.FirstOrDefaultAsync(p => p.Id == id);
                if (user != null) return View(user);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(User user)
        {
            db.Users.Update(user);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Library/Views/Book/Create.cshtml
@model Library.Models.Book

@using Library.Models
@using Library.ViewModels

<h2>Добавить книгу</h2>
<form asp-action="create" asp-controller="Book">
    <p>
        <label asp-for="Title">Название</label><br />
        <input type="text" asp-for="Title" />
    </p>
    <p>
        <label asp-for="Autor">Автор</label><br />
        <input type="text" asp-for="Autor" />
    </p>
    <p>
        <label asp-for="Genre">Жанр</label><br />
        <input type="text" asp-for="Genre" />
    </p>
    <p>
        <label asp-for="Description">Краткое описание</label><br />
        <input type="text" asp-for="Description" />
    </p>
    <p>
        <label asp-for="Rating">Рейтинг</label><br />
        <input type="number" asp-for="Rating" />
    </p>
    <p>
        <label asp-for="IsRead">Прочитана?</label><br />
        <input type="checkbox" asp-for="IsRead" />
    </p>
    <p>
    <label>Выберите пользователя:</label>

    <select name="userId">
           @*@foreach (var item in )
            {
                <option value="">Тут не могу показать список пользователей для привязки по внешнему ключу</option>
            }*@
        </select>
    <input type="number" asp-for="UserID" />
    </p>
    <p>
        <input type="submit" value="Отправить" />
    </p>
</form>

Library/Views/Book/Edit.cshtml
@model Library.Models.Book

<h2>Редактирование данных</h2>
<form asp-action="Edit" asp-controller="Book" asp-route-id="@Model.Id">
    <p>
        <label asp-for="Title">Название</label><br />
        <input type="text" asp-for="Title" />
    </p>
    <p>
        <label asp-for="Autor">Автор</label><br />
        <input type="text" asp-for="Autor" />
    </p>
    <p>
        <label asp-for="Genre">Жанр</label><br />
        <input type="text" asp-for="Genre" />
    </p>
    <p>
        <label asp-for="Description">Краткое описание</label><br />
        <input type="text" asp-for="Description" />
    </p>
    <p>
        <label asp-for="Rating">Рейтинг</label><br />
        <input type="number" asp-for="Rating" />
    </p>
    <p>
        <label asp-for="IsRead">Прочитана?</label><br />
        <input type="checkbox" asp-for="IsRead" />
    </p>
    <p>
        <label>Выберите пользователя:</label>

        <select name="userId">
            @*@foreach (var item in )
            {
            <option value="">Тут не могу показать список пользователей для привязки по внешнему ключу</option>
            }*@
        </select>
        <input type="number" asp-for="UserID" />
    </p>
    <p>
        <input type="submit" value="Отправить" />
    </p>
</form>

Library/Views/Book/Index.cshtml
@model IEnumerable<Library.Models.Book>

@{
    ViewData["Title"] = "Книжная полочка";
}


<h2>Список книг</h2>
<p><a asp-action="Create" asp-controller="Book">Добавить книгу</a></p>
<table class="table">
    <tr><th>Книга</th><th>Автор</th></tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Title</td>
            <td>@item.Autor</td>
            <td>
                <a asp-action="Edit" asp-controller="Book" asp-route-id="@item.Id">Изменить</a>
            </td>
            <td>
                <form asp-controller="Book" asp-action="Delete" method="post" asp-route-id="@item.Id">
                    <input type="submit" value="Удалить">
                </form>
            </td>
        </tr>
    }
</table>

Library/Views/Home/Create.cshtml
@using Library.Models
@using Library.ViewModels
@model IndexViewModel

@{
    ViewData["Title"] = "Home Page";
}


<h2>Книжные полки</h2>
<form>
    <label>Выберите пользователя:</label>
    <select name="userID">
        @foreach (UserModel user in Model.Users)
        {
            <option value="@user.id">@user.Name</option>
        }
    </select>
    <input type="submit" />
</form>
<br />
<table class="table">
    <tr>
        <th>Название</th>
        <th>Автор</th>
    </tr>
    @foreach (Book b in Model.Books)
    {
        <tr>
            <td>@b.Title</td>
            <td>@b.Autor</td>
        </tr>
    }
</table>

Library/Views/Home/Index.cshtml
@using Library.Models
@using Library.ViewModels
@model IndexViewModel

@{
    ViewData["Title"] = "Home Page";
}

<p><a asp-action="Index" asp-controller="User">Список пользователей</a></p>

<h2>Книжные полки</h2>
<form>
    <label>Выберите пользователя:</label>
    <select name="userID">
        @foreach(UserModel user in Model.Users)
        {
            <option value="@user.id">@user.Name</option>
        }
    </select>
    <input type="submit" />
</form>
<br />
<table class="table">
    <tr>
        <th>Название</th>
        <th>Автор</th>
    </tr>
    @foreach(Book b in Model.Books)
    {
        <tr>
            <td>@b.Title</td>
            <td>@b.Autor</td>
        </tr>
    }
</table>

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Книжная полка</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Книги у пользователей</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Пользователи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Список книг</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Library
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Library/Views/User/Create.cshtml
@model Library.Models.User

<h2>Добавить пользователя</h2>
<form asp-action="Create" asp-controller="User">
    <p>
        <label asp-for="Name">Имя пользователя</label>
        <input type="text" asp-for="Name" />
    </p>
    <p>
        <input type="submit" value="Отправить" />
    </p>
</form>

Library/Views/User/Edit.cshtml
@model Library.Models.User

<h2>Редатировать данные пользователя</h2>
<form asp-action="Edit" asp-controller="User" asp-route-id="@Model.Id">
    <p>
        <label asp-for="Name">Имя</label>
        <input type="text" asp-for="Name" />
    </p>
    <p>
        <input type="submit" value="Отправить" />
    </p>
</form>

Library/Views/User/Index.cshtml
@model IEnumerable<Library.Models.User>

@{
    ViewData["Title"] = "Пользователи";
}

<h2>Пользователи:</h2>
<p><a asp-action="Create">Добавить пользователя</a></p>
<table class="table">
    <tr><th>Имя</th></tr>
    @foreach (var item in Model)
    {
            <tr>
                <td>@item.Name</td>
                <td>
                    <a asp-action="Edit" asp-controller="User" asp-route-id="@item.Id">Изменить</a>
                </td>
                <td>
                    <form asp-action="Delete" asp-controller="User" asp-route-id="@item.Id" method="post">
                        <input type="submit" value="Удалить">
                    </form>
                </td>
            </tr>

    }
</table>